# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-08 11:14
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Temperature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_value', models.CharField(max_length=70)),
                ('created_time', models.TimeField(blank=True, default=datetime.datetime(2016, 11, 8, 11, 14, 35, 28098), verbose_name='created Time')),
            ],
        ),
    ]
